"""empty message

Revision ID: 32c5a24e2570
Revises: b80f43bfaec4
Create Date: 2024-04-04 12:58:01.134930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c5a24e2570'
down_revision = 'b80f43bfaec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewRecord', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['InterviewerId'], ['Id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewRecord', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
