"""empty message

Revision ID: 91e48ec34da1
Revises: 32c5a24e2570
Create Date: 2024-04-26 13:42:37.770672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e48ec34da1'
down_revision = '32c5a24e2570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadidateInfo', schema=None) as batch_op:
        batch_op.drop_constraint('cadidateInfo_AssigneeId_fkey', type_='foreignkey')
        batch_op.drop_constraint('cadidateInfo_RecruitmentProgressId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['AssigneeId'], ['Id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recruitmentProgress', ['RecruitmentProgressId'], ['Id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('interviewRecord', schema=None) as batch_op:
        batch_op.drop_constraint('interviewRecord_CandidateId_fkey', type_='foreignkey')
        batch_op.drop_constraint('interviewRecord_InterviewerId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['InterviewerId'], ['Id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'cadidateInfo', ['CandidateId'], ['Id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('recruitmentProgress', schema=None) as batch_op:
        batch_op.drop_constraint('recruitmentProgress_RecruitmentRequestId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recruitmentRequest', ['RecruitmentRequestId'], ['Id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('recruitmentRequest', schema=None) as batch_op:
        batch_op.drop_constraint('recruitmentRequest_RequesterId_fkey', type_='foreignkey')
        batch_op.drop_constraint('recruitmentRequest_AssigneeId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['AssigneeId'], ['Id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['RequesterId'], ['Id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitmentRequest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recruitmentRequest_AssigneeId_fkey', 'users', ['AssigneeId'], ['Id'])
        batch_op.create_foreign_key('recruitmentRequest_RequesterId_fkey', 'users', ['RequesterId'], ['Id'])

    with op.batch_alter_table('recruitmentProgress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recruitmentProgress_RecruitmentRequestId_fkey', 'recruitmentRequest', ['RecruitmentRequestId'], ['Id'])

    with op.batch_alter_table('interviewRecord', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('interviewRecord_InterviewerId_fkey', 'users', ['InterviewerId'], ['Id'])
        batch_op.create_foreign_key('interviewRecord_CandidateId_fkey', 'cadidateInfo', ['CandidateId'], ['Id'])

    with op.batch_alter_table('cadidateInfo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cadidateInfo_RecruitmentProgressId_fkey', 'recruitmentProgress', ['RecruitmentProgressId'], ['Id'])
        batch_op.create_foreign_key('cadidateInfo_AssigneeId_fkey', 'users', ['AssigneeId'], ['Id'])

    # ### end Alembic commands ###
