"""empty message

Revision ID: 94b1109afe92
Revises: 529374dfe2f8
Create Date: 2024-04-02 20:21:33.400829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b1109afe92'
down_revision = '529374dfe2f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruitmentRequest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('jobDescription', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('recruitmentType', sa.String(length=50), nullable=False),
    sa.Column('jobDuties', sa.Text(), nullable=False),
    sa.Column('requiredQualifications', sa.Text(), nullable=True),
    sa.Column('salaryAndBenefit', sa.Text(), nullable=False),
    sa.Column('expectedStartDate', sa.Date(), nullable=False),
    sa.Column('headCount', sa.Integer(), nullable=False),
    sa.Column('requesterId', sa.Integer(), nullable=False),
    sa.Column('hrId', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recruitmentProgressId', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['hrId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requesterId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruitmentRequest')
    # ### end Alembic commands ###
