"""empty message

Revision ID: b50ec4ce70fb
Revises: 
Create Date: 2024-04-03 15:37:02.695767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50ec4ce70fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=True),
    sa.Column('Role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('recruitmentRequest',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Position', sa.String(length=255), nullable=False),
    sa.Column('JobDescription', sa.Text(), nullable=True),
    sa.Column('City', sa.String(length=255), nullable=False),
    sa.Column('Department', sa.String(length=255), nullable=False),
    sa.Column('RecruitmentType', sa.String(length=50), nullable=False),
    sa.Column('JobDuties', sa.Text(), nullable=False),
    sa.Column('RequiredQualifications', sa.Text(), nullable=True),
    sa.Column('SalaryAndBenefit', sa.Text(), nullable=False),
    sa.Column('ExpectedStartDate', sa.Date(), nullable=False),
    sa.Column('HeadCount', sa.Integer(), nullable=False),
    sa.Column('RequesterId', sa.Integer(), nullable=False),
    sa.Column('AssigneeId', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('RecruitmentProgressId', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['AssigneeId'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['RequesterId'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('recruitmentProgress',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RecruitmentRequestId', sa.Integer(), nullable=False),
    sa.Column('Position', sa.String(length=50), nullable=False),
    sa.Column('NumberOfNewHire', sa.Integer(), nullable=False),
    sa.Column('NewHires', sa.Text(), nullable=True),
    sa.Column('RecruitmentStartDate', sa.Date(), nullable=True),
    sa.Column('RecruitmentCompleteDate', sa.Date(), nullable=True),
    sa.Column('Status', sa.Enum('INPROGRESS', 'COMPLETE', name='progressstatus'), nullable=True),
    sa.ForeignKeyConstraint(['RecruitmentRequestId'], ['recruitmentRequest.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('cadidateInfo',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('RecruitmentProgressId', sa.Integer(), nullable=False),
    sa.Column('ResumeEvaluation', sa.Enum('PASSED', 'REJECTED', 'EVALUATED', name='resumeevaluationenum'), nullable=True),
    sa.Column('InterviewProgress', sa.Enum('PASSED_1', 'FAIL_1', 'PASSED_2', 'FAIL_2', 'WAITING_1', 'WAITING_2', name='interviewprogressenum'), nullable=True),
    sa.Column('OfferStatus', sa.Enum('ISSUED', 'REJECTED', name='offerstatusenum'), nullable=True),
    sa.Column('HiringStatus', sa.Enum('HIRED', 'NOT_HIRED', name='hiringstatusenum'), nullable=True),
    sa.Column('SubmissionChannel', sa.Enum('COMPANY_WEBSITE', 'INTERNALLY_REFERRED', 'LINKEDIN', name='submissionchannelenum'), nullable=True),
    sa.Column('Resume', sa.String(length=255), nullable=True),
    sa.Column('AssigneeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AssigneeId'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['RecruitmentProgressId'], ['recruitmentProgress.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cadidateInfo')
    op.drop_table('recruitmentProgress')
    op.drop_table('recruitmentRequest')
    op.drop_table('users')
    # ### end Alembic commands ###
