"""empty message

Revision ID: cc8d7585e5d6
Revises: b50ec4ce70fb
Create Date: 2024-04-03 16:23:57.199364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8d7585e5d6'
down_revision = 'b50ec4ce70fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadidateInfo', schema=None) as batch_op:
        batch_op.alter_column('RecruitmentProgressId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('AssigneeId',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('recruitmentProgress', schema=None) as batch_op:
        batch_op.alter_column('RecruitmentRequestId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Position',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('NumberOfNewHire',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('recruitmentRequest', schema=None) as batch_op:
        batch_op.alter_column('Position',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('City',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('Department',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('RecruitmentType',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('JobDuties',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('SalaryAndBenefit',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ExpectedStartDate',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('HeadCount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('RequesterId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('AssigneeId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('RecruitmentProgressId',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitmentRequest', schema=None) as batch_op:
        batch_op.alter_column('RecruitmentProgressId',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('Status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('AssigneeId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('RequesterId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('HeadCount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ExpectedStartDate',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('SalaryAndBenefit',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('JobDuties',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('RecruitmentType',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('Department',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('City',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('Position',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('recruitmentProgress', schema=None) as batch_op:
        batch_op.alter_column('NumberOfNewHire',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('Position',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('RecruitmentRequestId',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cadidateInfo', schema=None) as batch_op:
        batch_op.alter_column('AssigneeId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('RecruitmentProgressId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
